require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config/**/*'
    - 'spec/**/*'

Documentation: # Disabling documentation cop
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/ClassAndModuleChildren:
  Enabled: false
